<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Volo.Abp.Core" Version="10.6.1" />
    <PackageVersion Include="Volo.Abp.Ddd.Application" Version="10.6.1" />
    <PackageVersion Include="Volo.Abp.Ddd.Application.Contracts" Version="10.6.1" />
    <PackageVersion Include="Volo.Abp.Ddd.Domain" Version="10.6.1" />
    <PackageVersion Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="10.6.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" />
  </ItemGroup>
</Project>
