<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac" Version="10.6.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../modules/catalog/src/BomPraTi.Catalog/BomPraTi.Catalog.csproj" />
    <ProjectReference Include="../../modules/media/src/BomPraTi.Media/BomPraTi.Media.csproj" />
    <ProjectReference Include="../../modules/sellers/src/BomPraTi.Sellers/BomPraTi.Sellers.csproj" />
    <ProjectReference Include="../../modules/marketplace/src/BomPraTi.Marketplace/BomPraTi.Marketplace.csproj" />
  </ItemGroup>
</Project>
